spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true

  application:
    name: eurekaclient
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:${server.port}
mybatis:
  mapper-locations: classpath*:mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
